# World Health Organization Data

## Global Health Observatory

* [Data query API](https://apps.who.int/gho/data/node.resources.api)
* [GHO OData API ](https://www.who.int/data/gho/info/gho-odata-api)

Para se determinar o tipo de informação para acesso veja a [lista de dimensões e códigos](https://apps.who.int/gho/athena/api/GHO). Utilize o código disponível no campo `<Code label="">`. Por exemplo, no campo `<Code Label="WHOSIS_000001">` é possível encontrar o código `WHOSIS_000001` que indica `Life expectancy at birth (years)`.

Depois de estabelecida a informação, podem ser configurados parâmetros, com o sufixo `?` depois da URL. Os parâmetros são separados por `?`.

Os códigos dos países são encontrados em: [https://apps.who.int/gho/athena/api/COUNTRY](https://apps.who.int/gho/athena/api/COUNTRY).

## Importando dados em JSON no Python

![JSON](https://github.com/santanche/lab2learn/blob/master/api/json.png?raw=1)

In [8]:
import io
import requests
import json
url = "https://apps.who.int/gho/athena/api/GHO/WHOSIS_000001?filter=COUNTRY:BRA&format=json"
js = requests.get(url).content
#print(js.decode("utf-8"))

## Importando dados em CSV no Python

![CSV](https://github.com/santanche/lab2learn/blob/master/api/csv.png?raw=1)

In [ ]:
import pandas as pd
import io
import requests
url = "https://apps.who.int/gho/athena/api/GHO/WHOSIS_000001?filter=COUNTRY:BRA&format=csv"
data = requests.get(url).content
csv = pd.read_csv(io.StringIO(data.decode("utf-8")))
print(csv)

              GHO PUBLISHSTATE  ...  High                                   Comments
0   WHOSIS_000001    PUBLISHED  ...   NaN  WHO life table method: Vital registration
1   WHOSIS_000001    PUBLISHED  ...   NaN  WHO life table method: Vital registration
2   WHOSIS_000001    PUBLISHED  ...   NaN  WHO life table method: Vital registration
3   WHOSIS_000001    PUBLISHED  ...   NaN  WHO life table method: Vital registration
4   WHOSIS_000001    PUBLISHED  ...   NaN  WHO life table method: Vital registration
5   WHOSIS_000001    PUBLISHED  ...   NaN  WHO life table method: Vital registration
6   WHOSIS_000001    PUBLISHED  ...   NaN  WHO life table method: Vital registration
7   WHOSIS_000001    PUBLISHED  ...   NaN  WHO life table method: Vital registration
8   WHOSIS_000001    PUBLISHED  ...   NaN  WHO life table method: Vital registration
9   WHOSIS_000001    PUBLISHED  ...   NaN  WHO life table method: Vital registration
10  WHOSIS_000001    PUBLISHED  ...   NaN  WHO life table method: Vital registration
11  WHOSIS_000001    PUBLISHED  ...   NaN  WHO life table method: Vital registration
12  WHOSIS_000001    PUBLISHED  ...   NaN  WHO life table method: Vital registration
13  WHOSIS_000001    PUBLISHED  ...   NaN  WHO life table method: Vital registration
14  WHOSIS_000001    PUBLISHED  ...   NaN  WHO life table method: Vital registration
15  WHOSIS_000001    PUBLISHED  ...   NaN  WHO life table method: Vital registration
16  WHOSIS_000001    PUBLISHED  ...   NaN  WHO life table method: Vital registration
17  WHOSIS_000001    PUBLISHED  ...   NaN  WHO life table method: Vital registration
18  WHOSIS_000001    PUBLISHED  ...   NaN  WHO life table method: Vital registration
19  WHOSIS_000001    PUBLISHED  ...   NaN  WHO life table method: Vital registration
20  WHOSIS_000001    PUBLISHED  ...   NaN  WHO life table method: Vital registration
21  WHOSIS_000001    PUBLISHED  ...   NaN  WHO life table method: Vital registration
22  WHOSIS_000001    PUBLISHED  ...   NaN  WHO life table method: Vital registration
23  WHOSIS_000001    PUBLISHED  ...   NaN  WHO life table method: Vital registration
24  WHOSIS_000001    PUBLISHED  ...   NaN  WHO life table method: Vital registration
25  WHOSIS_000001    PUBLISHED  ...   NaN  WHO life table method: Vital registration
26  WHOSIS_000001    PUBLISHED  ...   NaN  WHO life table method: Vital registration
27  WHOSIS_000001    PUBLISHED  ...   NaN  WHO life table method: Vital registration
28  WHOSIS_000001    PUBLISHED  ...   NaN  WHO life table method: Vital registration
29  WHOSIS_000001    PUBLISHED  ...   NaN  WHO life table method: Vital registration
30  WHOSIS_000001    PUBLISHED  ...   NaN  WHO life table method: Vital registration
31  WHOSIS_000001    PUBLISHED  ...   NaN  WHO life table method: Vital registration
32  WHOSIS_000001    PUBLISHED  ...   NaN  WHO life table method: Vital registration
33  WHOSIS_000001    PUBLISHED  ...   NaN  WHO life table method: Vital registration
34  WHOSIS_000001    PUBLISHED  ...   NaN  WHO life table method: Vital registration
35  WHOSIS_000001    PUBLISHED  ...   NaN  WHO life table method: Vital registration
36  WHOSIS_000001    PUBLISHED  ...   NaN  WHO life table method: Vital registration
37  WHOSIS_000001    PUBLISHED  ...   NaN  WHO life table method: Vital registration
38  WHOSIS_000001    PUBLISHED  ...   NaN  WHO life table method: Vital registration
39  WHOSIS_000001    PUBLISHED  ...   NaN  WHO life table method: Vital registration
40  WHOSIS_000001    PUBLISHED  ...   NaN  WHO life table method: Vital registration
41  WHOSIS_000001    PUBLISHED  ...   NaN  WHO life table method: Vital registration
42  WHOSIS_000001    PUBLISHED  ...   NaN  WHO life table method: Vital registration
43  WHOSIS_000001    PUBLISHED  ...   NaN  WHO life table method: Vital registration
44  WHOSIS_000001    PUBLISHED  ...   NaN  WHO life table method: Vital registration
45  WHOSIS_000001    PUBLISHED  ...   NaN  WHO life table method: Vital registration
46  WHOSIS_000001    PUBLISHED  ...   NaN  WHO life table method: Vital registration
47  WHOSIS_000001    PUBLISHED  ...   NaN  WHO life table method: Vital registration
48  WHOSIS_000001    PUBLISHED  ...   NaN  WHO life table method: Vital registration
49  WHOSIS_000001    PUBLISHED  ...   NaN  WHO life table method: Vital registration
50  WHOSIS_000001    PUBLISHED  ...   NaN  WHO life table method: Vital registration

[51 rows x 11 columns]

# Importando dados em XML no Python

![XML](https://github.com/santanche/lab2learn/blob/master/api/xml.png?raw=1)

In [ ]:
import io
import requests
import xml.etree.ElementTree as et
url = "https://apps.who.int/gho/athena/api/GHO/WHOSIS_000001?filter=COUNTRY:BRA"
data = requests.get(url).content
x = et.parse(io.StringIO(data.decode("utf-8")))
print(x)

<xml.etree.ElementTree.ElementTree object at 0x7ff09babdf28>

# Tarefa 1

Das fontes de dados disponíveis, tente encontrar fontes com formatos diferentes e importá-las via Python. Busque pelo menos dois formatos.

In [14]:
import requests
import json
data = requests.get("https://covid19-brazil-api.now.sh/api/report/v1").json()
print(f"lista de casos por estado brasileiro: {data['data']}")
print("\n\n\n\n\n")
print(f"lista de casos no estado de São Paulo: {list(filter(lambda x: x['uf'] == 'SP', data['data']))[0]}")

lista de casos por estado brasileiro: [{'uid': 35, 'uf': 'SP', 'state': 'São Paulo', 'cases': 937332, 'deaths': 33984, 'suspects': 5334, 'refuses': 596, 'datetime': '2020-09-21T22:34:21.879Z'}, {'uid': 29, 'uf': 'BA', 'state': 'Bahia', 'cases': 295996, 'deaths': 6313, 'suspects': 573, 'refuses': 36, 'datetime': '2020-09-21T22:34:21.879Z'}, {'uid': 31, 'uf': 'MG', 'state': 'Minas Gerais', 'cases': 271194, 'deaths': 6727, 'suspects': 925, 'refuses': 104, 'datetime': '2020-09-21T22:34:21.879Z'}, {'uid': 33, 'uf': 'RJ', 'state': 'Rio de Janeiro', 'cases': 252046, 'deaths': 17727, 'suspects': 1254, 'refuses': 148, 'datetime': '2020-09-21T22:34:21.879Z'}, {'uid': 23, 'uf': 'CE', 'state': 'Ceará', 'cases': 234120, 'deaths': 8834, 'suspects': 493, 'refuses': 89, 'datetime': '2020-09-21T22:34:21.879Z'}, {'uid': 15, 'uf': 'PA', 'state': 'Pará', 'cases': 220775, 'deaths': 6468, 'suspects': 43, 'refuses': 23, 'datetime': '2020-09-21T22:34:21.879Z'}, {'uid': 42, 'uf': 'SC', 'state': 'Santa Catarina', 'cases': 206332, 'deaths': 2656, 'suspects': 346, 'refuses': 47, 'datetime': '2020-09-21T22:34:21.879Z'}, {'uid': 52, 'uf': 'GO', 'state': 'Goiás', 'cases': 185359, 'deaths': 4164, 'suspects': 353, 'refuses': 55, 'datetime': '2020-09-21T22:34:21.879Z'}, {'uid': 53, 'uf': 'DF', 'state': 'Distrito Federal', 'cases': 184555, 'deaths': 3097, 'suspects': 327, 'refuses': 107, 'datetime': '2020-09-21T22:34:21.879Z'}, {'uid': 43, 'uf': 'RS', 'state': 'Rio Grande do Sul', 'cases': 175349, 'deaths': 4409, 'suspects': 416, 'refuses': 330, 'datetime': '2020-09-21T22:34:21.879Z'}, {'uid': 21, 'uf': 'MA', 'state': 'Maranhão', 'cases': 167948, 'deaths': 3664, 'suspects': 125, 'refuses': 13, 'datetime': '2020-09-21T22:34:21.879Z'}, {'uid': 41, 'uf': 'PR', 'state': 'Paraná', 'cases': 165494, 'deaths': 4146, 'suspects': 400, 'refuses': 119, 'datetime': '2020-09-21T22:34:21.879Z'}, {'uid': 26, 'uf': 'PE', 'state': 'Pernambuco', 'cases': 141777, 'deaths': 8016, 'suspects': 89, 'refuses': 23, 'datetime': '2020-09-21T22:34:21.879Z'}, {'uid': 13, 'uf': 'AM', 'state': 'Amazonas', 'cases': 131920, 'deaths': 3964, 'suspects': 18, 'refuses': 26, 'datetime': '2020-09-21T22:34:21.879Z'}, {'uid': 32, 'uf': 'ES', 'state': 'Espírito Santo', 'cases': 125098, 'deaths': 3432, 'suspects': 71, 'refuses': 21, 'datetime': '2020-09-21T22:34:21.879Z'}, {'uid': 25, 'uf': 'PB', 'state': 'Paraíba', 'cases': 116879, 'deaths': 2719, 'suspects': 85, 'refuses': 11, 'datetime': '2020-09-21T22:34:21.879Z'}, {'uid': 51, 'uf': 'MT', 'state': 'Mato Grosso', 'cases': 114041, 'deaths': 3245, 'suspects': 45, 'refuses': 8, 'datetime': '2020-09-21T22:34:21.879Z'}, {'uid': 22, 'uf': 'PI', 'state': 'Piauí', 'cases': 90617, 'deaths': 2038, 'suspects': 12, 'refuses': 2, 'datetime': '2020-09-21T22:34:21.879Z'}, {'uid': 27, 'uf': 'AL', 'state': 'Alagoas', 'cases': 84720, 'deaths': 2024, 'suspects': 43, 'refuses': 22, 'datetime': '2020-09-21T22:34:21.879Z'}, {'uid': 28, 'uf': 'SE', 'state': 'Sergipe', 'cases': 76073, 'deaths': 1987, 'suspects': 15, 'refuses': 11, 'datetime': '2020-09-21T22:34:21.879Z'}, {'uid': 24, 'uf': 'RN', 'state': 'Rio Grande do Norte', 'cases': 67217, 'deaths': 2352, 'suspects': 108, 'refuses': 22, 'datetime': '2020-09-21T22:34:21.879Z'}, {'uid': 50, 'uf': 'MS', 'state': 'Mato Grosso do Sul', 'cases': 64033, 'deaths': 1179, 'suspects': 93, 'refuses': 26, 'datetime': '2020-09-21T22:34:21.879Z'}, {'uid': 17, 'uf': 'TO', 'state': 'Tocantins', 'cases': 63544, 'deaths': 867, 'suspects': 13, 'refuses': 0, 'datetime': '2020-09-21T22:34:21.879Z'}, {'uid': 11, 'uf': 'RO', 'state': 'Rondônia', 'cases': 63267, 'deaths': 1305, 'suspects': 61, 'refuses': 2, 'datetime': '2020-09-21T22:34:21.879Z'}, {'uid': 14, 'uf': 'RR', 'state': 'Roraima', 'cases': 48330, 'deaths': 613, 'suspects': 9, 'refuses': 0, 'datetime': '2020-09-21T22:34:21.879Z'}, {'uid': 16, 'uf': 'AP', 'state': 'Amapá', 'cases': 46946, 'deaths': 693, 'suspects': 15, 'refuses': 0, 'datetime': '2020-09-21T22:34:21.879Z'}, {'uid': 12, 'uf': 'AC', 'state': 'Acre', 'cases': 27106, 'deaths': 649, 'suspects': 12, 'refuses': 0, 'datetime': '2020-09-21T22:34:21.879Z'}]






lista de casos no estado de São Paulo: {'uid': 35, 'uf': 'SP', 'state': 'São Paulo', 'cases': 937332, 'deaths': 33984, 'suspects': 5334, 'refuses': 596, 'datetime': '2020-09-21T22:34:21.879Z'}

In [13]:
import pandas as pd
data = pd.read_csv("https://data.cityofnewyork.us/resource/fcau-jc6k.csv")
print("primeiras linhas:")
print(data.head())
print("\n\n\ntabela inteira:")
data

primeiras linhas:
   year  ... number_of_live_births
0  2016  ...                  7159
1  2016  ...                 21566
2  2016  ...                  1534
3  2016  ...                 22465
4  2016  ...                 40633

[5 rows x 9 columns]



tabela inteira:

    year  ... number_of_live_births
0   2016  ...                  7159
1   2016  ...                 21566
2   2016  ...                  1534
3   2016  ...                 22465
4   2016  ...                 40633
5   2016  ...                 26915
6   2015  ...                  7561
7   2015  ...                 40607
8   2015  ...                  1781
9   2015  ...                 23116
10  2015  ...                 20535
11  2015  ...                 27994
12  2014  ...                 20746
13  2014  ...                 27753
14  2014  ...                  7897
15  2014  ...                  1485
16  2014  ...                 40443
17  2014  ...                 23680
18  2013  ...                 19767
19  2013  ...                 27621
20  2013  ...                 24108
21  2013  ...                  1349
22  2013  ...                  7960
23  2013  ...                 39573
24  2012  ...                  1468
25  2012  ...                 39112
26  2012  ...                 27969
27  2012  ...                 24758
28  2012  ...                  8673
29  2012  ...                 21149
30  2011  ...                 25825
31  2011  ...                 28643
32  2011  ...                  8988
33  2011  ...                  1444
34  2011  ...                 38573
35  2011  ...                 19399
36  2010  ...                 18047
37  2010  ...                 26635
38  2010  ...                 37780
39  2010  ...                  9581
40  2010  ...                 29764
41  2010  ...                  2719
42  2009  ...                  9958
43  2009  ...                 17729
44  2009  ...                 38438
45  2009  ...                 27405
46  2009  ...                  2653
47  2009  ...                 30328
48  2008  ...                 38383
49  2008  ...                 27917
50  2008  ...                 18204
51  2008  ...                 30029
52  2008  ...                  2548
53  2008  ...                 10351
54  2007  ...                 30483
55  2007  ...                 19291
56  2007  ...                   230
57  2007  ...                 10229
58  2007  ...                 29268
59  2007  ...                 39351

[60 rows x 9 columns]

# Tarefa 2

## Engenharia reversa

Monte um diagramas que representem modelos dos dados que você terá acesso e como pretende associá-los. Coloque abaixo uma imagem do diagrama.

Podemos perceber que existem varios pontos em comum entre o consumo de alcool e a ocorrencia de doenças cardiovasculares. Podemos ainda ampliar o estudo e relacionar como a condição financeira influencia esses fatores

![Image](../images/tarefa2.png)